name: Build Configs

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main,stable,dev ]
  pull_request:
    branches: [ main,stable,dev ]
  workflow_dispatch:

env:
  PLATFORMIO_VER: 6.1.4

jobs:
  Build-Default:
    name: Build Default Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [G32,N32]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Run OS Update & Install PlatformIO
      run: |
        sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y
        python -m pip install --upgrade pip
        pip install wheel
        pip install platformio==$PLATFORMIO_VER
    - name: Run PlatformIO
      id: build_configs
      env:
        AQUILA_VER: ${{ matrix.chip }}
        FIRMWARE_NAME_PARAMS: ${{ matrix.chip }}
        FIRMWARE_NAME: Default-NoProbe-${{ env.FIRMWARE_NAME_PARAMS }}.bin
      run: FIRMWARE_NAME=${{ env.FIRMWARE_NAME }} make -f Makefile.voxelab Default-NoProbe
    - name: Upload Build Binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.FIRMWARE_NAME }}
        path: .pio/build/STM32F103RET6_voxelab_aquila_${{ matrix.chip }}/${{ env.FIRMWARE_NAME }}
  
  Build-BLTouch:
    name: Build BL-Touch Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [G32,N32]
        grid: [3,4,5,9]
        highspeed: [true,false]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Run OS Update & Install PlatformIO
      run: |
        sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y
        python -m pip install --upgrade pip
        pip install wheel
        pip install platformio==$PLATFORMIO_VER
    - name: Run PlatformIO
      id: build_configs
      env:
        AQUILA_VER: ${{ matrix.chip }}
        GRID: ${{ matrix.grid }}
        HS: ${{ matrix.highspeed }}
        FIRMWARE_NAME_PARAMS: ${{ matrix.grid }}x${{ matrix.grid }}${{ matrix.highspeed == 'true' && '-HS' || '' }}-${{ matrix.chip }}
        FIRMWARE_NAME: BLTouch-${{ env.FIRMWARE_NAME_PARAMS }}.bin
      run: FIRMWARE_NAME=${{ env.FIRMWARE_NAME }} make -f Makefile.voxelab BLTouch
    - name: Upload Build Binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.FIRMWARE_NAME }}
        path: .pio/build/STM32F103RET6_voxelab_aquila_${{ matrix.chip }}/${{ env.FIRMWARE_NAME }}
  
  Build-ManualMesh:
    name: Build Manual-Mesh Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [G32,N32]
        grid: [3,4,5]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Run OS Update & Install PlatformIO
      run: |
        sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y
        python -m pip install --upgrade pip
        pip install wheel
        pip install platformio==$PLATFORMIO_VER
    - name: Run PlatformIO
      id: build_configs
      env:
        AQUILA_VER: ${{ matrix.chip }}
        GRID: ${{ matrix.grid }}
        FIRMWARE_NAME_PARAMS: ${{ matrix.grid }}x${{ matrix.grid }}-${{ matrix.chip }}
        FIRMWARE_NAME: ManualMesh-${{ env.FIRMWARE_NAME_PARAMS }}.bin
      run: FIRMWARE_NAME=${{ env.FIRMWARE_NAME }} make -f Makefile.voxelab ManualMesh
    - name: Upload Build Binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.FIRMWARE_NAME }}
        path: .pio/build/STM32F103RET6_voxelab_aquila_${{ matrix.chip }}/${{ env.FIRMWARE_NAME }}
 
  Build-UBL-BLTouch:
    name: Build UBL with BL-Touch Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [G32,N32]
        grid: [10,15]
        highspeed: [true,false]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Run OS Update & Install PlatformIO
      run: |
        sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y
        python -m pip install --upgrade pip
        pip install wheel
        pip install platformio==$PLATFORMIO_VER
    - name: Run PlatformIO
      id: build_configs
      env:
        AQUILA_VER: ${{ matrix.chip }}
        GRID: ${{ matrix.grid }}
        HS: ${{ matrix.highspeed }}
        FIRMWARE_NAME_PARAMS: ${{ matrix.grid }}x${{ matrix.grid }}${{ matrix.highspeed == 'true' && '-HS' || '' }}-${{ matrix.chip }}
        FIRMWARE_NAME: UBL-BLTouch-${{ env.FIRMWARE_NAME_PARAMS }}.bin
      run: FIRMWARE_NAME=${{ env.FIRMWARE_NAME }} make -f Makefile.voxelab UBL-BLTouch
    - name: Upload Build Binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.FIRMWARE_NAME }}
        path: .pio/build/STM32F103RET6_voxelab_aquila_${{ matrix.chip }}/${{ env.FIRMWARE_NAME }}
  
  Build-UBL-NoProbe:
    name: Build UBL with NoProbe Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [G32,N32]
        grid: [3,5]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Run OS Update & Install PlatformIO
      run: |
        sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y
        python -m pip install --upgrade pip
        pip install wheel
        pip install platformio==$PLATFORMIO_VER
    - name: Run PlatformIO
      id: build_configs
      env:
        AQUILA_VER: ${{ matrix.chip }}
        GRID: ${{ matrix.grid }}
        FIRMWARE_NAME_PARAMS: ${{ matrix.grid }}x${{ matrix.grid }}-${{ matrix.chip }}
        FIRMWARE_NAME: UBL-NoProbe-${{ env.FIRMWARE_NAME_PARAMS }}.bin
      run: FIRMWARE_NAME=${{ env.FIRMWARE_NAME }} make -f Makefile.voxelab UBL-NoProbe
    - name: Upload Build Binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.FIRMWARE_NAME }}
        path: .pio/build/STM32F103RET6_voxelab_aquila_${{ matrix.chip }}/${{ env.FIRMWARE_NAME }}
